### ISSUE TITLE
OpenPHACTS v2.1

### ISSUE THREAD

**Issue by aessig** [openphacts/ops.js#25]
Is the library compatible with OpenPHACTS v2.1 ? If not, is there any project about making it ?

**Comment by ianwdunlop** [comment]
It's "mostly " compatible. There are bound to be some bits of decay. It doesn't have any of the new API calls added after 1.5. The easiest way to check is to point it at a 2.1 API and run the tests (see the README for info). There is no current project developing it but you never know what could happen in the  future......

**Comment by egonw** [comment]
(so, if you need a particular method, at least file a feature request for it... I will likely use it for the programming in the life sciences course this autumn again. As such, I may have a bit of time to implement some missing things... no promises, though!)

**Comment by Chris-Evelo** [comment]
Some of these new calls are ours (for pathway directionality), could we maybe also add these as part of that course?

   Best, Chris
-
Prof.Dr. Chris Evelo
Dept. Head Bioinformatics - BiGCaT
Maastricht University

**Comment by aessig** [comment]
Thank you for your help 👍

**Comment by egonw** [comment]
Hi all, @aessig, the develop branch is now 2.1 compatible... I have added a client method for getInteractions, but I guess there are more new API methods missing. There are four real regressions, but these are caused by the API timing out, not by problems in the ops.js library.

@aessig, which methods do you use for which you like client methods added?

**Comment by egonw** [comment]
Version 7.0.0 is developed for and testing against OPS 2.1.
